# Generated by Django 4.0.1 on 2022-01-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeadmin', '0002_partner_partnership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financeadmin.partner'),
        ),
    ]
