# Generated by Django 4.0.1 on 2022-01-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeadmin', '0005_alter_profit_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
