# Generated by Django 4.0.1 on 2022-01-29 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeadmin', '0007_alter_profit_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnerpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('created_date', models.CharField(max_length=30)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeadmin.partner')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeadmin.profit')),
            ],
        ),
    ]
